version: "3.7"
services:
  devcontainer:
    image: devimages/eoan-xfce-novnc
    privileged: true
    ports:
      - "6080:6080"
    shm_size: 1gb
    volumes: 
      - devhome:/home/developer
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  devhome:
    local: true