version: "3.7"
services:
  devcontainer:
    build: .
    image: devimages/eoan-xfce-novnc:latest
    working_dir: /home/developer/
    privileged: true
    ports:
      - "6080:6080"
    shm_size: 1gb
    command: bash -c "supervisord && sleep infinity"
    volumes: 
      - devhome-eoan-xfce-novnc:/home/developer:rw
      - /var/run/docker.sock:/var/run/docker.sock
  devcontainerTagged:
    build: .
    image: devimages/eoan-xfce-novnc:${npm_package_version}
volumes:
  devhome-eoan-xfce-novnc:
    external: true