version: "3.7"
services:
  devcontainer:
    build: .
    privileged: true
    ports:
      - "6080:6080"
    shm_size: 1gb
    command: sleep infinity
    volumes: 
      - devhome:/home/developer
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  devhome:
    driver: local