version: "3.7"
services:
  devcontainer:
    build: .
    image: devimages/disco-frontend-basic:${npm_package_version}
    privileged: true
    ports:
      - "6080:6080"
    shm_size: 1gb
    command: bash -c "supervisord && sleep infinity"
    volumes: 
      - devcontainer-home:/home/developer
volumes:
  devcontainer-home:
    external: true