version: "3.7"
services:
  devcontainer:
    build: .
    working_dir: .
    image: zolika84/devcontainer:${npm_package_tagName}
    privileged: true
    ports:
      - "6080:6080"
    shm_size: 1gb
    command: bash -c "supervisord && sleep infinity"
    volumes: 
      - devcontainer-home:/home/developer:rw
  devcontainer-semver:
    build: .
    image: zolika84/devcontainer:${npm_package_tagName}-${npm_package_version}
volumes:
  devcontainer-home:
    external: true