version: "3.7"
services:
  devcontainer:
    image: devimages/stretch-node-dotnet-cypress
    privileged: true
    ports:
      - "6080:6080"
    shm_size: 1gb
    volumes: 
      - devhome:/root/workspace
volumes:
  devhome:
    driver: local