version: "3.7"
services:
  devcontainer:
    build:
      context: .
      args:
        - UID=${UID}
        - GID=${GID}
    privileged: true
    environment:
      - UID=${UID}
      - GID=${GID}
    user: "${UID}:${GID}"
    ports:
      - "6080:6080"
    shm_size: 1gb
    volumes: 
      - devhome:/home/dev/workspace
volumes:
  devhome:
    driver: local