version: "3.7"
services:
  x11-bridge:
    image: devimages/x11-xpra-html5:latest
    ports:
      - "10000:14500"
    volumes:
      - x11:/tmp/.X11-unix
    environment:
      - MODE=tcp
      - XPRA_HTML=yes
      - DISPLAY=:14 
  devcontainer:
    build: .
    privileged: true
    shm_size: 1gb
    environment: 
      - DISPLAY=:14
    volumes: 
      - devhome:/home/dev/workspace
      - x11:/tmp/.X11-unix
volumes:
  devhome:
    driver: local
  x11:
    driver: local