name: Node CI

on: [push]

jobs:
  build:
    runs-on: node:12
    steps:
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
